document.addEventListener('DOMContentLoaded', () => {
    const cacheNameInput = document.getElementById('cacheName');
    const cacheCodeInput = document.getElementById('cacheCode');
    const ftfNameInput = document.getElementById('ftfName');
    const stfNameInput = document.getElementById('stfName');
    const ttfNameInput = document.getElementById('ttfName');
    const showSTF = document.getElementById('showSTF');
    const showTTF = document.getElementById('showTTF');
    const stfGroup = document.getElementById('stfGroup');
    const ttfGroup = document.getElementById('ttfGroup');
    const podiumColor = document.getElementById('podiumColor');
    const podiumSize = document.getElementById('podiumSize');
    const podiumPreview = document.getElementById('podiumPreview');
    const podiumCode = document.getElementById('podiumCode');
    const copyBtn = document.getElementById('copyBtn');

    const pathParts = window.location.pathname.split('/');
    let currentLang = 'en';
    if (pathParts.includes('fr')) currentLang = 'fr';
    if (pathParts.includes('de')) currentLang = 'de';

    const translations = {
        en: { generated: "Generated by SpeedyGeoTools.com" },
        fr: { generated: "Généré par SpeedyGeoTools.com" },
        de: { generated: "Erstellt mit SpeedyGeoTools.com" }
    };

    const config = {
        small: { maxW: '280px', titleF: '14px', emoji1: '18px', mainF: '14px', subF: '12px', pad: '10px' },
        medium: { maxW: '380px', titleF: '16px', emoji1: '24px', mainF: '18px', subF: '14px', pad: '20px' },
        large: { maxW: '500px', titleF: '20px', emoji1: '32px', mainF: '22px', subF: '18px', pad: '25px' }
    };

    function getProfileLink(username) {
        if (!username || username === '...') return username;
        return `<a href="https://www.geocaching.com/p/default.aspx?u=${encodeURIComponent(username)}" target="_blank" rel="noopener noreferrer" style="color: inherit; text-decoration: underline;">${username}</a>`;
    }

    function generate() {
        if (!podiumPreview || !podiumCode) return;

        const name = cacheNameInput ? (cacheNameInput.value.trim() || 'Geocaching.com') : 'Geocaching.com';
        const code = cacheCodeInput ? cacheCodeInput.value.trim().toUpperCase() : '';
        const color = podiumColor ? podiumColor.value : '#02874D';
        const size = podiumSize ? podiumSize.value : 'medium';
        
        const c = config[size] || config['medium'];
        const lang = translations[currentLang] || translations['fr'];

        const ftf = getProfileLink(ftfNameInput ? (ftfNameInput.value.trim() || '...') : '...');
        const stf = getProfileLink(stfNameInput ? (stfNameInput.value.trim() || '...') : '...');
        const ttf = getProfileLink(ttfNameInput ? (ttfNameInput.value.trim() || '...') : '...');

        const cacheUrl = code ? `https://coord.info/${code}` : '#';

        let html = `<div style="font-family: Arial, sans-serif; max-width: ${c.maxW}; width: 100%; border: 2px solid ${color}; border-radius: 12px; background: #ffffff; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.1);">\n`;
        html += `    <div style="background: ${color}; padding: ${c.pad}; text-align: center;">\n`;
        html += `        <a href="${cacheUrl}" target="_blank" rel="noopener noreferrer" style="color: white; text-decoration: none; font-weight: bold; font-size: ${c.titleF};">${name}</a>\n`;
        if (code) html += `        <div style="color: rgba(255,255,255,0.8); font-size: 11px; margin-top: 3px;">${code}</div>\n`;
        html += `    </div>\n`;
        html += `    <div style="padding: ${c.pad}; text-align: center;">\n`;
        html += `        <div style="margin-bottom: 15px;">\n`;
        html += `            <div style="font-size: ${c.emoji1}; margin-bottom: 5px;">🥇</div>\n`;
        html += `            <div style="font-weight: bold; color: #333; font-size: ${c.mainF};">FTF</div>\n`;
        html += `            <div style="color: ${color}; font-size: ${c.mainF}; font-weight: bold;">${ftf}</div>\n`;
        html += `        </div>\n`;

        if (showSTF && showSTF.checked) {
            html += `        <div style="display: flex; justify-content: space-around; border-top: 1px solid #eee; margin-top: 15px; padding-top: 15px;">\n`;
            html += `            <div>\n`;
            html += `                <div style="font-size: ${c.emoji1}; transform: scale(0.8);">🥈</div>\n`;
            html += `                <div style="font-weight: bold; color: #666; font-size: ${c.subF};">STF</div>\n`;
            html += `                <div style="color: #444; font-weight: 600; font-size: ${c.subF};">${stf}</div>\n`;
            html += `            </div>\n`;

            if (showTTF && showTTF.checked) {
                html += `            <div>\n`;
                html += `                <div style="font-size: ${c.emoji1}; transform: scale(0.8);">🥉</div>\n`;
                html += `                <div style="font-weight: bold; color: #666; font-size: ${c.subF};">TTF</div>\n`;
                html += `                <div style="color: #444; font-weight: 600; font-size: ${c.subF};">${ttf}</div>\n`;
                html += `            </div>\n`;
            }
            html += `        </div>\n`;
        }

        html += `        <div style="margin-top: 20px; padding-top: 10px; border-top: 1px solid #f9f9f9; text-align: center;">\n`;
        html += `            <a href="https://speedygeotools.com" target="_blank" rel="noopener noreferrer" style="font-size: 10px; color: #bbb; text-decoration: none;">${lang.generated}</a>\n`;
        html += `        </div>\n`;
        html += `    </div>\n`;
        html += `</div>`;

        podiumPreview.innerHTML = html;
        podiumCode.value = html;
    }

    const triggers = [cacheNameInput, cacheCodeInput, ftfNameInput, stfNameInput, ttfNameInput, podiumColor, podiumSize, showSTF, showTTF];
    triggers.forEach(el => {
        if (el) {
            el.addEventListener('input', () => {
                if (el === showSTF || el === showTTF) {
                    if (stfGroup && showSTF) stfGroup.style.display = showSTF.checked ? 'block' : 'none';
                    if (ttfGroup && showTTF) ttfGroup.style.display = showTTF.checked ? 'block' : 'none';
                    if (showSTF && !showSTF.checked) {
                        if (showTTF) showTTF.checked = false;
                        if (ttfGroup) ttfGroup.style.display = 'none';
                    }
                }
                generate();
            });
        }
    });

    if (copyBtn) {
        copyBtn.addEventListener('click', () => {
            if (!podiumCode || !podiumCode.value) return;
            navigator.clipboard.writeText(podiumCode.value).then(() => {
                const original = copyBtn.textContent;
                copyBtn.textContent = '✔️ Copié !';
                copyBtn.style.backgroundColor = '#02874D';
                setTimeout(() => { 
                    copyBtn.textContent = original;
                    copyBtn.style.backgroundColor = '';
                }, 2000);
            });
        });
    }

    generate();
});